### ISSUE TITLE
Edits pass through manuscript

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler-manuscripts#13]
I'm taking an edit pass through the manuscript (excluding Results) right now!  Can't check in until I land due to bandwidth limitations, however.

**Comment by danielparton** [comment]
Thanks for the edits and comments! I've revised the "Design and Implementation" section accordingly. I just pushed to master - hope that's ok. Let me know if you want me to PR instead in the future.
Introduction is next.

**Comment by jchodera** [comment]
Thanks! Pushing to master is fine.
