### ISSUE TITLE
Plan for entering references

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler-manuscripts#15]
There are still a huge number of references to be filled in.  What was your plan for this?

**Comment by danielparton** [comment]
Was going to work on the text more before filling them in.

**Comment by jchodera** [comment]
Thanks! Just wanted to know if you were waiting for me to fill these in.

**Comment by jchodera** [comment]
How about we switch to adding references as we go along?

**Comment by jchodera** [comment]
Also, can we add the PDFs of the references to Zotero (as you collect them)?

**Comment by danielparton** [comment]
Sure, will do
