### ISSUE TITLE
Fix font size issues in figures

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler-manuscripts#18]
All of the plots have font size issues.  Mostly, the fonts are far too small.

Figure guidelines are here:
http://www.ploscompbiol.org/static/figureSpecifications

All fonts must be 6 points at minimum. I think the best way to ensure this is to use `matplotlib` to render the figures to the correct column width and specify 6-point (or desired) font size.

**Comment by danielparton** [comment]
Fixed.
