### ISSUE TITLE
Use Oxford (serial) comma throughout

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler-manuscripts#19]
This is universally used in scientific writing.

**Comment by jhprinz** [comment]
"I learned something today". This is good to know!

**Comment by danielparton** [comment]
I have now fixed this where necessary

**Comment by sonyahanson** [comment]
Ironically, the only time I ever didn't use the Oxford comma was when I was in Oxford... Maybe it's a British thing? My advisor (Simon, not Mark), certainly advised against the Oxford comma in my thesis.
