### ISSUE TITLE
Updated outline of introduction

### ISSUE THREAD

**Issue by jchodera** [choderalab/ensembler-manuscripts#2]
I've updated the Introduction section of the google docs outline.  Hopefully, this provides some helpful ideas!

**Comment by jchodera** [comment]
Any progress on the introduction, @danielparton?

**Comment by danielparton** [comment]
I've added in your text from the google docs outline. It looks good to me, so I haven't added anything major - just a few small edits, and one comment (marked 'TODO') for you to look at.
