### ISSUE TITLE
Check figure, table and SI numbering schemes are correct

### ISSUE THREAD

**Issue by danielparton** [choderalab/ensembler-manuscripts#21]
Do this at the end of the manuscript-writing process.
The SI documents will likely be in a range of different formats, so I expect building a system to automatically link these numberings would be difficult or unnecessarily time-consuming.

**Comment by jchodera** [comment]
The simplest approach is just to append the SI as an Appendix for now,
using the \label and \ref schemes for now. We can separate this later.

Let's not use any manual schemes for keeping numberings consistent.

**Comment by danielparton** [comment]
Ok, I've moved the residue numbering schemes text to an appendix in the main doc.
