### ISSUE TITLE
Figure: distribution of remodeled loop lengths

### ISSUE THREAD

**Issue by danielparton** [choderalab/ensembler-manuscripts#25]
Here is an updated version of the figure, as per John's suggestions (copied below):

![](https://github.com/choderalab/ensembler-manuscripts/raw/262a029c6718b71277625d949e5a1a9389abc408/figures/loopmodel_analysis/nmissing_resis_distributions.png)

Note that I removed the rug plots ("ticks"). Also note that the rug plot is something implemented in seaborn which simply plots a line (tick) of given length for each data point, along the x-axis. If there are multiple data points with the same value, the corresponding tick does not change in length or thickness.

Previous version:

![](https://github.com/choderalab/ensembler-manuscripts/raw/c75d7a48f90ebd013a356a880a6c1c74406e18cd/figures/loopmodel_analysis/nmissing_resis_distributions.png)

John's comments from the manuscript:

Some ideas for cleaning this up: Either the tick marks are being misrendered in that they are not taller if there are multiple data points with the same number or the data is really funky, since I would expect there to be a few ex- amples in some bins. Also, is there a big drawback to making the top histogram bin size unity, since the values are integral? I don’t think transparency is needed for the histogram bars either. We can also ditch the semilogy axis. I would also make the x-axes for the top and bottom plots different, since the data ranges are different. I’d see if a histogram with unit bin size might be more appropriate for the bottom plot as well—the KDE just doesn’t feel right for this kind of data, since we are trying to report exact statistics from a specific example rather than estimate a general density for prob- lems of this sort. Finally, I like “remodeled loop length” or “missing loop length” much better than “Number of missing residues per template gap”, which seems unnecessarily verbose.

**Comment by danielparton** [comment]
New version following offline comments with John:

![](https://github.com/choderalab/ensembler-manuscripts/raw/fcb5d557ddbbf152d30de0681392742692e68b71/figures/loopmodel_analysis/nmissing_resis_distributions.png)

**Comment by jchodera** [comment]
Do you think we need to label the y-axes?
- `number of templates`
- `number of loops`?

**Comment by danielparton** [comment]
Yes, I think this helps. Updated:

![](https://github.com/choderalab/ensembler-manuscripts/raw/facaa207a03b5002c967b17967e4e4526ee4e4bf/figures/loopmodel_analysis/nmissing_resis_distributions.png)

**Comment by jchodera** [comment]
Thanks!
