### ISSUE TITLE
Analysis of potential energies from implicit solvent MD refinement

### ISSUE THREAD

**Issue by danielparton** [choderalab/ensembler-manuscripts#26]
kde-smoothed distributions of final energies, across all 373513 models which completed 100 ps implicit refinement successfully:

![](https://github.com/choderalab/ensembler-manuscripts/raw/e670a762204fb19e8bbcdf4a9cf5cd2e035904e2/figures/energies/energies.png)

Statistics for the above (all models):

```
min      -14180.260000
median    -9533.431000
max       -3589.644000
std        1058.190905
```

Statistics for the 9 models which failed implicit refinement, but reported final energies (note that energies are reported every 1 ps):

```
min     -10746.201000
median   -8772.646000
max      -7243.606000
std        971.757140
```

25448 models failed implicit refinement without reporting energies, i.e. failed within 1 ps.

So based on this data alone, I think it would not seem to be particularly useful to use the energies to identify and filter out poor models, as these tend to fail very quickly.

It might be interesting in future to look at the correlation between these energies and the energies (or failure rates) from explicit solvent simulations, either within ensembler or in production simulations.

**Comment by jchodera** [comment]
This looks good!

> So based on this data alone, I think it would not seem to be particularly useful to use the energies to identify and filter out poor models, as these tend to fail very quickly.

Agreed.

> It might be interesting in future to look at the correlation between these energies and the energies (or failure rates) from explicit solvent simulations, either within ensembler or in production simulations.

Potentially!  But given the energies here are all negative and there is no obvious high-energy peak, I don't think there is a pressing need to do this analysis right now.

**Comment by danielparton** [comment]
I think we can close this?

**Comment by jchodera** [comment]
OK!
