### ISSUE TITLE
Link API/CLI code mentioned in text to a specific Ensembler release.

### ISSUE THREAD

**Issue by danielparton** [choderalab/ensembler-manuscripts#35]
"The specific command-line flags and API details discussed in this paper correspond to the version [TODO] release (TODO: link)."

I'll plan to make a new Ensembler release just before we submit to a journal.

**Comment by danielparton** [comment]
I've added this at the beginning of the Design & Implementation section

**Comment by jchodera** [comment]
Thanks!
