### ISSUE TITLE
Split sections into separate files

### ISSUE THREAD

**Issue by danielparton** [choderalab/ensembler-manuscripts#7]
For example, the Introduction would be in introduction.tex

A master file (ms.tex) would include the Introduction with `\input{introduction}`

I think this would be useful for collaborative editing, as each section will be in a different file.

Sound good?

**Comment by jchodera** [comment]
I don't think this is necessary! Should be fine if we work on one section at a time.

**Comment by danielparton** [comment]
Ok, I'll leave it as is
